const  songs = [
    {
        songName: "Heather",
        artist: "Conan Gray",
        genre: "Indie pop, Musik rakyat, Pop",
        thumbnail: "heather-conangray.jpg",
        video: "conangray-heather.mp4",
        lirik: ``,
        chord: ``,
        video_chord: "tutorgitarheather-conangray.mp4",
    },
    {
        songName: "Here With Me",
        artist: "D4vd",
        genre: "Alternatif/Indie, Pop, UK R&B",
        thumbnail: "here with me.jpg",
        video: "d4vd-herewithme.mp4",
        lirik: ``,
        chord: ``,
        video_chord: "tutorgitarherewithme-d4vd.mp4",
    },
    {
        songName: "Pumped Up Kicks",
        artist: "Foster the People",
        genre: "Electropop",
        thumbnail: "pumped up kicks.jpg",
        video: "fosterthepeople-pumpedupkicks.mp4",
        lirik: ``,
        chord: ``,
        video_chord: "tutorgitarpumpedupkicks-fosterthepeople.mp4",
    },
    {
        songName: "Golden Hour",
        artist: "JVKE",
        genre: "Musik pop, Alternatif/Indie",
        thumbnail: "golden hour.jpg",
        video: "jvke-goldenhour.mp4",
        lirik: ``,
        chord: ``,
        video_chord: "tutorgitargoldenhour-jvke.mp4",
    },
    {
        songName: "I Don't Love You",
        artist: "My Chemical Romance",
        genre: "Emo, Rok alternatif, Alternatif/Indie, Rock",
        thumbnail: "i dont love you.jpg",
        video: "mychemicalromance-idontloveyou.mp4",
        lirik: ``,
        chord: ``,
        video_chord: "tutorgitaridontloveyou-mychemicalromance.mp4",
    },
    {
        songName: "To The Bone",
        artist: "Pamungkas",
        genre: "Indonesian Indie, Indonesian Pop",
        thumbnail: "to the bone.jpg",
        video: "pamungkas-tothebone.mp4",
        lirik: ``,
        chord: ``,
        video_chord: "tutorgitartothebone-pamungkas.mp4",
    },
    {
        songName: "No Surprises",
        artist: "Radiohead",
        genre: "Alternatif/Indie, Dream pop",
        thumbnail: "no surprises.jpg",
        video: "radiohead-nosurprises.mp4",
        lirik: ``,
        chord: ``,
        video_chord: "tutorgitarradiohead-nosurprises.mp4",
    },
    {
        songName: "Anything You Want",
        artist: "Reality Club",
        genre: "Musik pop, French Indie, Pop, Thai Indie, Indonesian Indie",
        thumbnail: "anything you want.jpg",
        video: "realityclub-anythingyouwant.mp4",
        lirik: ``,
        chord: ``,
        video_chord: "tutorgitaranythingyouwant-realityclub.mp4",
    },
    {
        songName: "Feels Like We Only Go Backwards",
        artist: "Tame Impala",
        genre: "Alternatif/Indie",
        thumbnail: "tame impala.jpg",
        video: "tameimpala-feelslikeweonlygo.mp4",
        lirik: ``,
        chord: ``,
        video_chord: "tutorgitarfeelslikeweonlygobackwards-tameimpala.mp4",
    },
    {
        songName: "Walking Back Home",
        artist: "Vira Talisa Dharmawan",
        genre: "Indonesian Indie",
        thumbnail: "walking back home.jpg",
        video: "viratalisadharmawan-walkingbackhome.mp4",
        lirik: ``,
        chord: ``,
        video_chord: "tutorwalkingbackhome-viratalisa.mp4",
    },
]

module.exports = songs